### ISSUE TITLE
tooltips show too much, gets in the way of selection

### ISSUE THREAD

**Issue by prjemian** [nexpy/nexpy#122]
In the tree view of loaded data, a tooltip appears when the cursor lingers over an item.  This tooltip shows the full tree view from that point of the HDF5 file.  For files with much depth (such as the example file 33bm_spec.dat, converted into HDF5 of course), this rich content gets in the way of selecting from the next items in the tree view.

By default, the tooltip should be concise, not verbose.  
Generalizing this goal to be concise for any of the 98 different NXDL classes will be a challenge.  A good first approximation to generality is for the tree view to be first descendants only with added ellipese if additional depth is discovered.  

A settings selection could be used to control the verbosity.

**Comment by rayosborn** [comment]
I think that having just one additional depth would be too restrictive, since hovering over the root would just give one entry each time. I will remove attributes from the tree. At the moment, if the output is longer than 50 lines, it does that, but I think I will make it the default, especially as the number of attributes is increasing, and we can see them with 'View Data'. Of course, even one line will obscure the line below, so it's really a case of how fast the tooltips refresh. Removing attributes will help that.

**Comment by rayosborn** [comment]
PR nexpy/nexusformat#41 modifies the underlying API so that the `short_tree` function returns a tree with two levels of recursion without attributes. This will be the default for tooltips in the next NeXpy release, which should make them more compact.
