### ISSUE TITLE
problems with importing sardana spec files

### ISSUE THREAD

**Issue by jkotan** [nexpy/nexpy#152]
During my tests I wanted to import a SPEC file created by [sardana](https://github.com/sardana-org/sardana/blob/develop/src/sardana/macroserver/recorders/storage.py#L270) , i.e. SCADA software developed at ALBA and hardly used by us (DESY) and other facilities, i.e. ALBA, MAX IV, SOLARIS, ...

A file example  can be found at  [here](https://github.com/jkotan/file-examples/blob/master/spec/my.spec)

It is not a problem of `nexpy` but rather [spec2nexus](https://github.com/prjemian/spec2nexus). Since I get it in `nexpy` I report it here.

**Comment by jkotan** [comment]
the mesage I get is

    ---------------------------------------------------------------------------
    NotASpecDataFile                          Traceback (most recent call last)
    /home/jkotan/testinst/lib/python2.7/site-packages/NeXpy-0.10.10+39.g9227249.dirty-py2.7.egg/nexpy/readers/readspec.pyc in choose_file(self)
	 92         if os.path.exists(filename):
	 93             self.filename.setText(str(filename))
    ---> 94             self.spec = SpecDataFile(self.get_filename())
	 95             self.set_default_directory(os.path.dirname(filename))
	 96             all_scans = self.get_scan_numbers()

    /home/jkotan/testinst/lib/python2.7/site-packages/spec2nexus-2017.901.4+10.g0ad8aa6-py2.7.egg/spec2nexus/spec.pyc in __init__(self, filename)
	207             raise SpecDataFileNotFound('file does not exist: ' + str(filename))
	208         if not is_spec_file(filename):
    --> 209             raise NotASpecDataFile('not a SPEC data file: ' + str(filename))
	210         self.fileName = filename
	211 

    NotASpecDataFile: not a SPEC data file: /home/jkotan/ndts/file-examples/spec/my.spec

**Comment by prjemian** [comment]
You identified this is a problem for spec2nexus.  I'm closing this issue here.  Please open an issue with that project (https://github.com/prjemian/spec2nexus/issues/new) and attach an example file that spec2nexus raises ``NotASpecDataFile``.  I'm not impressed with the error report from spec2nexus, it does not provide detail to understand what triggered the exception, only that this was identified during a call to ``SpecDataFile(self.get_filename())``.  That should also be improved.
