### ISSUE TITLE
problems with closing

### ISSUE THREAD

**Issue by jkotan** [nexpy/nexpy#159]
Hi,

From time to time (randomly) I get problem on closing nexpy. When I want to quit I get Widget "Are you sure you want to quit NexPy?" and after pressing "Quit" it hangs. The main widget does not disappear and  it does not react on mouse or keyboad. In order to close the NexPy I have to kill it. I use debian 9. 

Bests,
Jan

**Comment by jkotan** [comment]
It looks like the problem appears only for python3 (3.5). For python (2.7) I cannot reproduce the problem. As a workaround I will change my debian package to use 2.7.

**Comment by rayosborn** [comment]
This doesn't seem to happen on the linux systems I use regularly, although I have seen odd shutdown messages but without the freeze you report. I think there are three possible causes worth exploring, but I would probably need to create a separate branch for each of them if you would be willing to test them.
1) Some systems may be more sensitive to whether we have properly closed all the windows before quitting. There is a QApplication function to do that.
2) I am currently calling the QCoreApplication quit function rather than the QApplication quit function. The latter is for GUI applications, so perhaps it does more when quitting.
3) I need to explicitly call sys.exit(1) when I have closed everything else. I would have thought the quit function did that, but perhaps not.

**Comment by rayosborn** [comment]
There is possibly a fourth solution. I'm not sure I call the QMainwindow close function before quitting the QApplication event loop. I might try that first.

**Comment by rayosborn** [comment]
@jkotan, I decided to commit a possible fix directly to the v0.10.11 branch, since it was easier for me to test it on other Linux systems. On checking the PyQt documentation again, my previous method for quitting did not conform to their recommended practice, so I have made the necessary modifications. Please let me know if this fixes your problem, because it works on all my test systems (Py2 and 3) but none of them displayed exactly your symptoms.

**Comment by jkotan** [comment]
Unfortunately, it does not fix my issue. I've also noticed that the problem also exists for py 2.7. I will try to look at it next week.

**Comment by rayosborn** [comment]
I find that surprising, since I believe I am closely following the documentation. Does it only happen when you have multiple windows open? In the v0.10.11 branch, I have added closeAllWindows() to the QMainwindow closeEvent. This shouldn't be needed, but please check it in any case. If the freeze happens even with just the main window open, then it won't be relevant.

**Comment by jkotan** [comment]
After the fix it hangs much rare and in a different way. All the windows are closed but from time to time when I run nexpy from a linux terminal it does not return to its prompt.  The NexPy is still running , e.g.


      PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                    
    23875 jkotan    20   0 1370252 212424  78700 S  0.0  1.3   0:03.90 nexpy3                                     
    23879 jkotan    20   0 1370252 212424  78700 S  0.0  1.3   0:00.32 QXcbEventReader                            
    23880 jkotan    20   0 1370252 212424  78700 S  0.0  1.3   0:00.00 gmain                                      
    23881 jkotan    20   0 1370252 212424  78700 S  0.0  1.3   0:00.00 gdbus                                      
    23882 jkotan    20   0 1370252 212424  78700 S  0.0  1.3   0:00.00 QDBusConnection                            
    23884 jkotan    20   0 1370252 212424  78700 S  0.0  1.3   0:00.00 nexpy3                                     
    23885 jkotan    20   0 1370252 212424  78700 S  0.0  1.3   0:00.00 nexpy3   

To reproduce the issue I only run nexpy, open a nexus file, plot its data and close the nexpy. Usually it close correctly by for some cases (let say 1 per 10) I get hanging.

**Comment by rayosborn** [comment]
I found a [StackOverflow question](https://stackoverflow.com/questions/29421936/cant-quit-pyqt5-application-with-embedded-ipython-qtconsole) that suggested closing down the kernel explicitly. The second suggestion is to explicitly call `sys.exit()` after the QApplication has quit. I've merged both steps into the quit procedure on branch v0.10.11. This doesn't seem to cause any problems on Macs and our Linux cluster.

**Comment by jkotan** [comment]
The problem is still there.

**Comment by prjemian** [comment]
Are any threads still running?

**Comment by rayosborn** [comment]
Clearly PyQt is multi-threaded, and probably the IPython console, although NeXpy uses the in-process kernel. However, those should all be shut all those down. NeXpy doesn't launch any other threads.

**Comment by jkotan** [comment]
Hi,

I've just found a workaround for this problem, i.e


    diff --git a/src/nexpy/gui/consoleapp.py b/src/nexpy/gui/consoleapp.py
    index 2861ea0..c1bac17 100644
    --- a/src/nexpy/gui/consoleapp.py
    +++ b/src/nexpy/gui/consoleapp.py
    @@ -366,7 +366,6 @@ def main(filename=None):
         app = NXConsoleApp()
         app.initialize(filename=filename)
         app.start()
    -    sys.exit(0)


     if __name__ == '__main__':
    diff --git a/src/nexpy/nexpygui.py b/src/nexpy/nexpygui.py
    index 2a9d52f..5720d81 100755
    --- a/src/nexpy/nexpygui.py
    +++ b/src/nexpy/nexpygui.py
    @@ -23,6 +23,9 @@ def main():
         args = parser.parse_args()
         from nexpy.gui.consoleapp import main
         main(args.filename)
    +    import gc
    +    gc.set_debug(gc.DEBUG_SAVEALL)
    +    gc.collect()


     if __name__ == '__main__':

Important line is: `gc.set_debug(gc.DEBUG_SAVEALL)`, i.e. without it this workaround does not work.
It looks like something unreachable should be collected otherwise nexpy randomly hangs. It would be nice to find what is it.

**Comment by jkotan** [comment]
I could not to reproduce the bug on ubuntu 18.04 VM . So maybe this hanging comes from one of depending debian stretch packages, i.e. an unlucky version of package.

**Comment by rayosborn** [comment]
Thanks for the updates. I am fairly busy with experiments for the next couple of weeks, but I hope to make another release shortly after. I think this issue has already led to significant improvements in the shutdown process, but if you learn any more, I will try to take it into account.

**Comment by rayosborn** [comment]
Fixed by #162.
