### ISSUE TITLE
Axis error

### ISSUE THREAD

**Issue by jpcastell** [nexpy/nexpy#161]
I found an issue using projections.  When taking a 2d slice or 1d plot from a large data set where one of the axis has a space in the name ( such as "Energy Transfer"  ) , the projection does not retain the axis information afterwards.

**Comment by rayosborn** [comment]
I'm not sure that the NeXus format allows a space in the name of a field - in fact, I'm surprised that HDF5 allows it, but it seems to work, so I guess NeXpy should handle it. It's not just projections that have a problem. When you plot the data, the axis label is generic, *e.g.*, 'Axis0'. I'll look into it.

**Comment by rayosborn** [comment]
@jpcastell, I don't know if this is still a concern, but I should have mentioned when you first raised it that, if you want to have an axis label with spaces, this can be achieved without naming the NXfield with a space. If you define a field with the 'long_name' attribute, *e.g.*,
```
x=NXfield(np.linspace(0,10.,101), name='x', long_name='Energy Transfer')
data=NXdata(np.sin(x), x)
data.plot()
```
the axis plot label will be the 'long_name' attribute, not 'x'. This works for 1D projections as well. The issue you discovered is nothing to do with projections; it affects all 1D NXdata groups, because, in parsing the axis name, it assumes they represent multiple axes. I might produce a fix in the future, but it does violate the NeXus standard.
