### ISSUE TITLE
consider "plot zoom" as a stack

### ISSUE THREAD

**Issue by prjemian** [nexpy/nexpy#46]
The current "plot zoom" feature works great.  At present, the right mouse button is used to zoom back out.  

An enhancement would be for it to zoom back out to the previous level of magnification, which may not be all the way to full view.  Each time a region is selected for a zoom, the parameters of the previous would be pushed to a stack.  A right button click would take the parameters from the top of the stack (and pop that stack) rather than going to full view.

**Comment by rayosborn** [comment]
Thanks for the suggestion. If you go to the Options tab, then you should be able to get something like that with the forward and back buttons. Is that sufficient for your needs? Matplotlib provides such a stack, but its use in NeXpy breaks up the zooms into the x- and y-components, so you sometimes have to click more times than you expect. Right-clicking is equivalent to hitting the Home button. 

Because of the multiple-click issue, I think I would find it irritating to have to right-click through the stack. I usually use the right-click to restore the original image and would prefer just one click. I'm open to counter-opinions though.

**Comment by rayosborn** [comment]
Closed due to inactivity.

**Comment by tacaswell** [comment]
There is some upstream work to improve the toolbar.  As part of that the view history is being pulled out and (I think) the mpl version of this stack is getting a public API.

**Comment by rayosborn** [comment]
Thanks for the heads up. I'm always nervous of when dependencies refactor their code, but this will probably be a help in the long run.

**Comment by tacaswell** [comment]
An there you capture the tension in big projects ;).  People demand new features, but also demand than we change nothing.

In this case, it is less of a refactor and more of a re-write from scratch.

**Comment by rayosborn** [comment]
Does the mpl master branch contain the new toolbar code?

**Comment by tacaswell** [comment]
The new toolbar code will be in 1.5.0, but only for the gtk backend.
Porting it over to the other backends is waiting on a more extensive
refactoring of the backend figure_manager code.
