### ISSUE TITLE
Minor plot bug

### ISSUE THREAD

**Issue by jpcastell** [nexpy/nexpy#81]
I found this for the 2dmaps when axis1 and axis2 are vastly different scales.

ie axis 1 goes from 0-100 and axis 2 from .1-.2 the smaller range doesn't show any tick bars or numbering on the plot.

**Comment by rayosborn** [comment]
Thanks for pointing this out. That's a 'feature' that was introduced with skew axes. I had to reset the default ticks to the usual Matplotlib ones, because the skewed grid functions didn't use them. Unfortunately, I set the "integer" keyword in MaxNLocator to True, which restricts tick marks to integer values. I must have copied that from somewhere without knowing what it meant. You can produce the correct behavior with 

    from mpl_toolkits.axisartist.grid_helper_curvelinear import GridHelperCurveLinear
    from mpl_toolkits.axisartist.grid_finder import MaxNLocator
    locator = MaxNLocator(nbins=9, steps=[1, 2, 5, 10])
    plotview.grid_helper=GridHelperCurveLinear((plotview.transform, plotview.inverse_transform),
        grid_locator1=locator,  grid_locator2=locator)

It's an irritating bug, so I might issue a point release quickly to clear it.

**Comment by rayosborn** [comment]
I have issued a pull request, but I might move the locator into the NXPlotView instance so that it can be modified from the command line before merging.
